apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhWFpoYmtKaGVtRnVPbWRvY0Y4eFl6QXpXSE5KWjJ3elJrSTBWM2w1UVRsbmIyTndaRGRHVVZSQlJFSXpSVXRCYTA4PSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFYWmhibUpoZW1GdWIzWTZNVkV5ZHpObE5ISWhMZz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
